### ISSUE TITLE
data.py throwing error

### ISSUE THREAD

**Issue by danlaine** [GOCompetition/Evaluation#2]
I am trying to read in data using data.py but an exception is being raised.

Commands I'm running:
`python3`
(Now in the Python terminal)
`>>> import data`
`>>> d = data.Data()`
`>>> d.raw.read("Original_Dataset_1-1/Original_Dataset_Offline_Edition_1/Network_01-10/scenario_1/case.raw")`

I get the following stack printout:

missing field, row:  
['2', '1', '1', '1', '1', '27.292', '7.278', '0', '0', '0', '0', '1', '1']  
Traceback (most recent call last):  
  File ".../Evaluation/data.py", line 42, in pad_row  
    raise Exception('missing field not allowed')  
Exception: missing field not allowed  
Traceback (most recent call last):  
  File "<stdin>", line 1, in <module>  
  File ".../Evaluation/data.py", line 147, in read  
    self.read_from_rows(rows)  
  File ".../Evaluation/data.py", line 190, in read_from_rows  
    load.read_from_row(row)  
  File ".../Evaluation/data.py", line 892, in read_from_row  
    row = pad_row(row, 14)  
  File ".../Evaluation/data.py", line 52, in pad_row  
    raise e  
  File "/.../Evaluation/data.py", line 42, in pad_row  
    raise Exception('missing field not allowed')  
Exception: missing field not allowed

If I'm invoking this wrong, please provide example usage.

Cheers,
Dan

**Comment by danlaine** [comment]
Any idea when this issue might be resolved? I can't move forward with this competition until this is fixed.
